default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails-misses-cocktail_development

test:
  <<: *default
  database: rails-misses-cocktail_test
